import {useEffect} from 'react';
import {useRouter} from 'next/router';
import Head from 'next/head';
import Image from 'next/image';
import {parse} from 'query-string';

import useLocalStorage from '../hooks/use-local-storage';
import {spotifyLoginUrl} from '../auth/spotify';
import styles from '../styles/Home.module.css';

export default function Home() {
  const router = useRouter();
  const [spotifyTokenExpiry, setSpotifyTokenExpiry] = useLocalStorage(
    'spotifyTokenExpiry',
    0,
  );
  const [spotifyToken, setSpotifyToken] = useLocalStorage('spotifyToken', '');

  useEffect(() => {
    if (router.asPath.includes('access_token')) {
      // Get the auth code from here
      const {access_token, expires_in} = parse(
        router.asPath.replace(/\//g, ''),
      );
      setSpotifyToken(access_token as string);
      setSpotifyTokenExpiry(Number(expires_in) * 1000 + Date.now());
      router.replace('/');
    }
  }, [router, setSpotifyToken, setSpotifyTokenExpiry]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {spotifyTokenExpiry < Date.now() ? (
          <a className={styles.SignIn} href={spotifyLoginUrl}>
            Login to Spotify
          </a>
        ) : (
          <div>Logged in to Spotify ✅</div>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
