import Head from 'next/head';
import Image from 'next/image';
import useSpotifyToken from '../hooks/use-spotify-token';
import StationList from '../components/station-list';
import {spotifyLoginUrl} from '../auth/spotify';
import styles from '../styles/Home.module.css';

export default function Home() {
  const {isSpotifyTokenExpired} = useSpotifyToken();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {isSpotifyTokenExpired ? (
          <a className={styles.SignIn} href={spotifyLoginUrl}>
            Login to Spotify
          </a>
        ) : (
          <div>
            Logged in to Spotify ✅
            <br />
            <StationList />
          </div>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
